<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Inserta registros en la tabla clientes
        DB::table('clientes')->insert([
            [
                'nombreCliente' => 'Alejandro',
                'apellidoCliente' => 'Aguilar Castillo',
                'dniCliente' => '40277716',
                'correoCliente' => 'alejandro_ac94@gmail.com',
                'telefonoCliente' => '976830733',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Ana',
                'apellidoCliente' => 'Aguilar Mondoñedo',
                'dniCliente' => '45650699',
                'correoCliente' => 'anamondo95@gmail.com',
                'telefonoCliente' => '904839099',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Andrea',
                'apellidoCliente' => 'Apolaya Ballesteros',
                'dniCliente' => '43795809',
                'correoCliente' => 'andrea_apolaya@gmail.com',
                'telefonoCliente' => '917594691',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Ashley',
                'apellidoCliente' => 'Apaza Chacón',
                'dniCliente' => '44381005',
                'correoCliente' => 'ashleyapaza03@gmail.com',
                'telefonoCliente' => '913334034',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Carmen',
                'apellidoCliente' => 'Alayo Oyola',
                'dniCliente' => '42721304',
                'correoCliente' => 'carmen_alayo@gmail.com',
                'telefonoCliente' => '965028775',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Catherine',
                'apellidoCliente' => 'Álvarez Tarazona',
                'dniCliente' => '46664663',
                'correoCliente' => 'catherine_tara@gmail.com',
                'telefonoCliente' => '906549419',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Celia',
                'apellidoCliente' => 'Apolinar Luna',
                'dniCliente' => '46386309',
                'correoCliente' => 'celia_apolinar@gmail.com',
                'telefonoCliente' => '975609829',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Cherley',
                'apellidoCliente' => 'Arauco Altamirano',
                'dniCliente' => '41836133',
                'correoCliente' => 'cherleyarauco@gmail.com',
                'telefonoCliente' => '940749128',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Christian',
                'apellidoCliente' => 'Altamirano Asca',
                'dniCliente' => '40228355',
                'correoCliente' => 'christian_alt@gmail.com',
                'telefonoCliente' => '911078357',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Christopher',
                'apellidoCliente' => 'Aguilar Gómez',
                'dniCliente' => '43082118',
                'correoCliente' => 'chris_aguilar96@gmail.com',
                'telefonoCliente' => '902614087',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Cirila',
                'apellidoCliente' => 'Aucca Llanos',
                'dniCliente' => '43675128',
                'correoCliente' => 'cirila_all90@gmail.com',
                'telefonoCliente' => '931952498',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Clara',
                'apellidoCliente' => 'Alvarado Luna',
                'dniCliente' => '47135256',
                'correoCliente' => 'clarasayers95@gmail.com',
                'telefonoCliente' => '938682755',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'David',
                'apellidoCliente' => 'Acuña Alvarez',
                'dniCliente' => '41603952',
                'correoCliente' => 'david_acuna03@gmail.com',
                'telefonoCliente' => '970164371',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Diana',
                'apellidoCliente' => 'Arce Reyna',
                'dniCliente' => '72189551',
                'correoCliente' => 'dianaarce@gmail.com',
                'telefonoCliente' => '952869063',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Eduardo',
                'apellidoCliente' => 'Alva Rivasplata',
                'dniCliente' => '41754710',
                'correoCliente' => 'eduardoalva92@gmail.com',
                'telefonoCliente' => '936099246',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Elizabeth',
                'apellidoCliente' => 'Medina Gutiérrez',
                'dniCliente' => '41424808',
                'correoCliente' => 'elizabeth_abril@gmail.com',
                'telefonoCliente' => '983350788',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Elizabet',
                'apellidoCliente' => 'Alarco Huamani',
                'dniCliente' => '43763151',
                'correoCliente' => 'elizabetalarco@gmail.com',
                'telefonoCliente' => '941272901',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Emilio',
                'apellidoCliente' => 'Agreda Sierra',
                'dniCliente' => '44317207',
                'correoCliente' => 'emilio_agreda@gmail.com',
                'telefonoCliente' => '984256699',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Evelyn',
                'apellidoCliente' => 'Arellano Amaro',
                'dniCliente' => '41008818',
                'correoCliente' => 'evelynarellano96@gmail.com',
                'telefonoCliente' => '961539658',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Gladys',
                'apellidoCliente' => 'Alvarado Ortiz',
                'dniCliente' => '48679152',
                'correoCliente' => 'gladys_alvarado@gmail.com',
                'telefonoCliente' => '919064372',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Gloria',
                'apellidoCliente' => 'Benitez Lazaro',
                'dniCliente' => '46695621',
                'correoCliente' => 'gloriaa_beni92@gmail.com',
                'telefonoCliente' => '961227393',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Guadalupe',
                'apellidoCliente' => 'Aguilar Ojeda',
                'dniCliente' => '47639659',
                'correoCliente' => 'guadalupe_aguilar@gmail.com',
                'telefonoCliente' => '993646538',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Harold',
                'apellidoCliente' => 'Aburto Peñaloza',
                'dniCliente' => '45980957',
                'correoCliente' => 'haroldaburto94@gmail.com',
                'telefonoCliente' => '913632365',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Hannah',
                'apellidoCliente' => 'Anyosa Liu',
                'dniCliente' => '42854758',
                'correoCliente' => 'hannahanyosa@gmail.com',
                'telefonoCliente' => '988180821',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Hilda',
                'apellidoCliente' => 'Álvarez Artica',
                'dniCliente' => '46326357',
                'correoCliente' => 'hilda_alvarez@gmail.com',
                'telefonoCliente' => '947975728',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Iris',
                'apellidoCliente' => 'Arana Rios',
                'dniCliente' => '48224717',               
                'correoCliente' => 'irisarana96@gmail.com',
                'telefonoCliente' => '957659441',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Jaqueline',
                'apellidoCliente' => 'Arbulú Martínez',
                'dniCliente' => '40235216',
                'correoCliente' => 'jaqueline_arbulu@gmail.com',
                'telefonoCliente' => '943946763',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Jorge',
                'apellidoCliente' => 'Ahumada Mansilla',
                'dniCliente' => '47047167',
                'correoCliente' => 'jorgeahumada@gmail.com',
                'telefonoCliente' => '926349252',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Jorge',
                'apellidoCliente' => 'Hernández Deza',
                'dniCliente' => '41622822',
                'correoCliente' => 'jorge_hdeza10@gmail.com',
                'telefonoCliente' => '968664237',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'José',
                'apellidoCliente' => 'Alcázar Huamani',
                'dniCliente' => '43988265',
                'correoCliente' => 'jose_alcazar@gmail.com',
                'telefonoCliente' => '937881391',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Juan',
                'apellidoCliente' => 'Zubiate Vega',
                'dniCliente' => '46670451',
                'correoCliente' => 'juan_abrigo94@gmail.com',
                'telefonoCliente' => '944012915',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Julio',
                'apellidoCliente' => 'Agüero Salazar',
                'dniCliente' => '48625857',
                'correoCliente' => 'julio_guero@gmail.com',
                'telefonoCliente' => '915752448',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Katherine',
                'apellidoCliente' => 'Álvarez Avendaño',
                'dniCliente' => '42496056',
                'correoCliente' => 'katherinealvarez@gmail.com',
                'telefonoCliente' => '900312203',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Lidia',
                'apellidoCliente' => 'Apolino Pinares',
                'dniCliente' => '43435974',
                'correoCliente' => 'lidia_apolino@gmail.com',
                'telefonoCliente' => '954158052',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Liz',
                'apellidoCliente' => 'Apaza Ochoa',
                'dniCliente' => '44580035',
                'correoCliente' => 'lizapaza98@gmail.com',
                'telefonoCliente' => '950945212',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Lucrecia',
                'apellidoCliente' => 'Álvarez Paiva',
                'dniCliente' => '40733068',
                'correoCliente' => 'lucrecia_alvarez@gmail.com',
                'telefonoCliente' => '956185857',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'María',
                'apellidoCliente' => 'Acosta Villalobos',
                'dniCliente' => '43227252',
                'correoCliente' => 'mariaacostav@gmail.com',
                'telefonoCliente' => '982424982',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Marita',
                'apellidoCliente' => 'Álvarez Uscamayta',
                'dniCliente' => '47539531',
                'correoCliente' => 'maritaalvarez@gmail.com',
                'telefonoCliente' => '991728713',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Mónica',
                'apellidoCliente' => 'Llenque Flores',
                'dniCliente' => '45632034',
                'correoCliente' => 'monica_allende@gmail.com',
                'telefonoCliente' => '951146369',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Marycruz',
                'apellidoCliente' => 'Vera Quispe',
                'dniCliente' => '45099002',
                'correoCliente' => 'marycruz_antonio@gmail.com',
                'telefonoCliente' => '967958308',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Michael',
                'apellidoCliente' => 'Acosta Perez',
                'dniCliente' => '41421655',
                'correoCliente' => 'michaelacosta@gmail.com',
                'telefonoCliente' => '971519124',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Mónica',
                'apellidoCliente' => 'Arellano García',
                'dniCliente' => '45861608',
                'correoCliente' => 'monicaarellano95@gmail.com',
                'telefonoCliente' => '972494729',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Myriam',
                'apellidoCliente' => 'Arnez Centenaro',
                'dniCliente' => '48213051',
                'correoCliente' => 'myriam_arnez@gmail.com',
                'telefonoCliente' => '912300520',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Naomi',
                'apellidoCliente' => 'Alburquerque Cabanillas',
                'dniCliente' => '40447047',
                'correoCliente' => 'naomialburquerque@gmail.com',
                'telefonoCliente' => '989804432',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Nathaly',
                'apellidoCliente' => 'Ames Pizarro',
                'dniCliente' => '45481687',
                'correoCliente' => 'nathaly_ames@gmail.com',
                'telefonoCliente' => '973274705',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Nycollet',
                'apellidoCliente' => 'Altamirano Idrogo',
                'dniCliente' => '71204147',
                'correoCliente' => 'nycolletaltamirano@gmail.com',
                'telefonoCliente' => '957436879',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Oswaldo',
                'apellidoCliente' => 'Alegre Ángeles',
                'dniCliente' => '41926059',
                'correoCliente' => 'oswaldo_alegre@gmail.com',
                'telefonoCliente' => '954621779',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Paola',
                'apellidoCliente' => 'Albinagorta Inchicaqui',
                'dniCliente' => '40719714',
                'correoCliente' => 'paolaalbinagorta@gmail.com',
                'telefonoCliente' => '934508469',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Paulina',
                'apellidoCliente' => 'Aparicio Ramos',
                'dniCliente' => '45687841',
                'correoCliente' => 'paulina_aparicio@gmail.com',
                'telefonoCliente' => '978880214',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Ramón',
                'apellidoCliente' => 'Acuña Zuñiga',
                'dniCliente' => '15741718',
                'correoCliente' => 'ramonacuna@gmail.com',
                'telefonoCliente' => '996004556',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Raúl',
                'apellidoCliente' => 'Acosta Espinosa',
                'dniCliente' => '45841847',
                'correoCliente' => 'raul_acosta@gmail.com',
                'telefonoCliente' => '925040352',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Ricardo',
                'apellidoCliente' => 'Abad Almendras',
                'dniCliente' => '46776149',
                'correoCliente' => 'ricardoabad@gmail.com',
                'telefonoCliente' => '977759460',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Roxana',
                'apellidoCliente' => 'Aguirre Valencia',
                'dniCliente' => '48496351',
                'correoCliente' => 'roxanaaguirre@gmail.com',
                'telefonoCliente' => '965217135',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Sheyla',
                'apellidoCliente' => 'Achata Baldeón',
                'dniCliente' => '71225907',
                'correoCliente' => 'sheyla_achata@gmail.com',
                'telefonoCliente' => '933548402',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Silvia',
                'apellidoCliente' => 'Amaya Corrales',
                'dniCliente' => '43688536',
                'correoCliente' => 'silviaamaya@gmail.com',
                'telefonoCliente' => '922101071',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Silvia',
                'apellidoCliente' => 'Arroyo Ramos',
                'dniCliente' => '22517530',
                'correoCliente' => 'silviaarroyo@gmail.com',
                'telefonoCliente' => '953185173',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Susana',
                'apellidoCliente' => 'Ángeles Aliaga',
                'dniCliente' => '40434926',
                'correoCliente' => 'susanaangeles@gmail.com',
                'telefonoCliente' => '918903586',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Tania',
                'apellidoCliente' => 'Alcalde Deza',
                'dniCliente' => '32912507',
                'correoCliente' => 'taniaalcalde@gmail.com',
                'telefonoCliente' => '998441861',
                'tipo_genero_id' => 2,
            ],
            [
                'nombreCliente' => 'Víctor',
                'apellidoCliente' => 'Aldea Salas',
                'dniCliente' => '42664663',
                'correoCliente' => 'victor_aldea@gmail.com',
                'telefonoCliente' => '979014384',
                'tipo_genero_id' => 1,
            ],
            [
                'nombreCliente' => 'Victoria',
                'apellidoCliente' => 'Arce Córdova',
                'dniCliente' => '44277208',
                'correoCliente' => 'victoriaarce@gmail.com',
                'telefonoCliente' => '949872896',
                'tipo_genero_id' => 2,
            ]
        ]);
    }
}
